import type { PostProcessPreset } from './schema';
import {
  buildReplicaEnumPromptGroupContent,
  REPLICA_ENUM_PROMPT_GROUP_NAME,
} from './replica-enum-prompt-rules';

export const BUILTIN_PRESETS: PostProcessPreset[] = [
  {
    name: '空模板',
    tasks: [
      {
        id: 'empty-task',
        name: '空模板任务',
        enabled: true,
        stage: 1,
        extractInjectTags: ['result'],
        promptGroups: [
          {
            role: 'system',
            content: '你是工作流助手。根据上下文输出简短分析，包裹在 <result> 标签内。',
          },
          {
            role: 'user',
            content: '上一用户输入：\n$8\n\n当前 AI 回复：\n$7\n\n请输出 <result>...</result>',
          },
        ],
      },
    ],
    tagVariableInjectTemplate: '<post_process_data>\n{{result}}\n</post_process_data>',
    finalInjectTemplate: '',
    userInputEndInjectTemplate: '',
    contextTurnCount: 3,
    contextExtractRules: [],
    contextExcludeRules: [],
    plotWorldbookConfig: { source: 'character', manualSelection: [], enabledEntries: {} },
    taskPlotWorldbookOverridesEnabled: false,
    taskContextOverridesEnabled: false,
    memoryRecallRecentCount: 10,
    chatExtractTags: { user: [], assistant: [] },
    chatBodyTagReplaceRules: [],
    chatWorldbookWriteRules: [],
  },
  {
    name: '副本族与动态占位符示例',
    tasks: [
      {
        id: 'example-enum-item',
        name: '枚举 item',
        enabled: true,
        stage: 1,
        extractInjectTags: ['result'],
        mergeStrategy: 'concat',
        maxRetries: 3,
        minLength: 0,
        apiPresetName: '',
        apiPresetFallbackNames: [],
        apiPrimaryMaxConcurrency: 5,
        apiFallbackMaxConcurrencies: [],
        promptGroups: [
          {
            name: '',
            role: 'system',
            content:
              '你是工作流助手。根据当前 AI 回复识别物品名称。按「ReplicaEnum 输出规则」输出枚举 JSON；可先写简短分析，可选另输出 <result> 摘要。',
            enabled: true,
          },
          {
            name: REPLICA_ENUM_PROMPT_GROUP_NAME,
            role: 'system',
            content: buildReplicaEnumPromptGroupContent(),
            enabled: true,
          },
          {
            name: '',
            role: 'user',
            content:
              '当前 AI 回复：\n$7\n\n请按 ReplicaEnum 输出规则输出分析（可选）与 <ReplicaEnum>…</ReplicaEnum> 枚举 JSON（values 填真实物品名）。',
            enabled: true,
          },
        ],
        plotWorldbookMode: 'inherit',
        contextMode: 'inherit',
        structuredOutputMode: 'off',
      },
      {
        id: 'example-replica-family',
        name: '副本族处理',
        enabled: true,
        stage: 2,
        extractInjectTags: ['item@name'],
        mergeStrategy: 'concat',
        maxRetries: 3,
        minLength: 0,
        apiPresetName: '',
        apiPresetFallbackNames: [],
        apiPrimaryMaxConcurrency: 5,
        apiFallbackMaxConcurrencies: [],
        promptGroups: [
          {
            name: '',
            role: 'system',
            content:
              '你是工作流助手。当前实例标识：{{replica:val}}。请根据该物品输出处理结果，包裹在 <item name="…">…</item> 中，name 属性须与当前实例一致。',
            enabled: true,
          },
          {
            name: '',
            role: 'user',
            content:
              '当前物品名称：{{replica:val}}\n\n（若楼层已有该实例正文可参考）\n{{item@name}}\n\n请输出对应的 <item name="…">…</item>。',
            enabled: true,
          },
        ],
        plotWorldbookMode: 'inherit',
        contextMode: 'inherit',
        structuredOutputMode: 'off',
        syncAsReplicaFamily: true,
        replicaFamilySpec: 'item@name',
        replicaFamilyEnumSpec: 'item@name',
        replicaFamilyBaseName: '副本族处理',
        replicaFamilyScheduleMode: 'auto',
      },
      {
        id: 'example-replica-family-aside',
        name: '副本族旁注',
        enabled: true,
        stage: 2,
        extractInjectTags: ['note@name'],
        mergeStrategy: 'concat',
        maxRetries: 3,
        minLength: 0,
        apiPresetName: '',
        apiPresetFallbackNames: [],
        apiPrimaryMaxConcurrency: 5,
        apiFallbackMaxConcurrencies: [],
        promptGroups: [
          {
            name: '',
            role: 'system',
            content:
              '你是工作流助手。当前实例标识：{{replica:val}}。请为该物品写一句简短旁注，包裹在 <note name="…">…</note> 中，name 属性须与当前实例一致。提示词中的 {{item@name}} 仅标识副本族规格（与「副本族处理」共用 item@name）。',
            enabled: true,
          },
          {
            name: '',
            role: 'user',
            content:
              '当前物品名称：{{replica:val}}\n\n（规格占位，运行时替换为精确引用；首轮通常无楼层正文）\n{{item@name}}\n\n请输出对应的 <note name="…">…</note>。',
            enabled: true,
          },
        ],
        plotWorldbookMode: 'inherit',
        contextMode: 'inherit',
        structuredOutputMode: 'off',
        syncAsReplicaFamily: true,
        replicaFamilySpec: 'item@name',
        replicaFamilyEnumSpec: 'item@name',
        replicaFamilyBaseName: '副本族旁注',
        replicaFamilyScheduleMode: 'auto',
      },
      {
        id: 'example-aggregate-launched',
        name: '汇总 launched',
        enabled: true,
        stage: 3,
        extractInjectTags: ['result'],
        mergeStrategy: 'concat',
        maxRetries: 3,
        minLength: 0,
        apiPresetName: '',
        apiPresetFallbackNames: [],
        apiPrimaryMaxConcurrency: 5,
        apiFallbackMaxConcurrencies: [],
        promptGroups: [
          {
            name: '',
            role: 'system',
            content:
              '你是工作流助手。根据下方占位符展开结果，写一段简短汇总，包裹在 <result>…</result> 中。',
            enabled: true,
          },
          {
            name: '',
            role: 'user',
            content:
              '本轮全部 item（跨同 spec 副本族）：\n{{total:launched:item@name}}\n\n仅「副本族处理」：\n{{total:launched:item@name:副本族处理}}\n\n旁注 note：\n{{total:note@name}}\n\n「副本族处理」已启动后缀名：\n{{replica:launched:副本族处理}}\n\n请输出 <result>…</result>。',
            enabled: true,
          },
        ],
        plotWorldbookMode: 'inherit',
        contextMode: 'inherit',
        structuredOutputMode: 'off',
      },
    ],
    tagVariableInjectTemplate: '{{total:launched:item@name}}',
    finalInjectTemplate: 'FLOOR_INJECT:{{total:launched:item@name}}',
    userInputEndInjectTemplate: '',
    chatExtractTags: { user: [], assistant: [] },
    chatBodyTagReplaceRules: [],
    chatWorldbookWriteRules: [
      {
        id: 'example-wb-item-name',
        targetTag: 'item@name',
        template: '{{total:launched:item@name}}',
        entryType: 'keyword',
        splitByAttr: true,
        bookSource: 'character',
      },
    ],
    contextTurnCount: 3,
    contextExtractRules: [],
    contextExcludeRules: [],
    plotWorldbookConfig: { source: 'character', manualSelection: [], enabledEntries: {} },
    taskPlotWorldbookOverridesEnabled: false,
    taskContextOverridesEnabled: false,
    memoryRecallRecentCount: 10,
  },
  {
    name: '正文润色示例',
    tasks: [
      {
        id: 'example-body-polish',
        name: '正文润色',
        enabled: true,
        stage: 1,
        extractInjectTags: ['content'],
        mergeStrategy: 'concat',
        maxRetries: 3,
        minLength: 0,
        apiPresetName: '',
        apiPresetFallbackNames: [],
        apiPrimaryMaxConcurrency: 5,
        apiFallbackMaxConcurrencies: [],
        promptGroups: [
          {
            name: '',
            role: 'system',
            content:
              '你是文学润色助手。根据待润色正文进行文学化润色，保持剧情与人设一致，不增删关键情节。只输出一个 <content>…</content> 块，不要其他说明文字。',
            enabled: true,
          },
          {
            name: '',
            role: 'user',
            content: '上一用户输入：\n$8\n\n待润色正文：\n$7',
            enabled: true,
          },
        ],
        plotWorldbookMode: 'inherit',
        contextMode: 'inherit',
        structuredOutputMode: 'off',
      },
    ],
    tagVariableInjectTemplate: '',
    finalInjectTemplate: '',
    userInputEndInjectTemplate: '',
    chatExtractTags: { user: [], assistant: ['content'] },
    chatBodyTagReplaceRules: [
      {
        id: 'example-content-replace',
        targetTag: 'content',
        template: '{{content}}',
      },
    ],
    chatWorldbookWriteRules: [],
    contextTurnCount: 1,
    contextExtractRules: [
      { start: '<tp', end: '</tp>' },
      { start: '<content', end: '</content>' },
    ],
    contextExcludeRules: [],
    plotWorldbookConfig: { source: 'character', manualSelection: [], enabledEntries: {} },
    taskPlotWorldbookOverridesEnabled: false,
    taskContextOverridesEnabled: false,
    memoryRecallRecentCount: 10,
  },
];

export function getDefaultSettingsPartial() {
  const preset = BUILTIN_PRESETS[0];
  return {
    tasks: preset.tasks,
    tagVariableInjectTemplate: preset.tagVariableInjectTemplate,
    finalInjectTemplate: preset.finalInjectTemplate,
    userInputEndInjectTemplate: preset.userInputEndInjectTemplate ?? '',
    contextTurnCount: preset.contextTurnCount,
    contextExtractRules: preset.contextExtractRules,
    contextExcludeRules: preset.contextExcludeRules,
    plotWorldbookConfig: preset.plotWorldbookConfig,
    taskPlotWorldbookOverridesEnabled: preset.taskPlotWorldbookOverridesEnabled ?? false,
    taskContextOverridesEnabled: preset.taskContextOverridesEnabled ?? false,
    memoryRecallRecentCount: preset.memoryRecallRecentCount ?? 10,
    presets: BUILTIN_PRESETS,
    activePresetName: preset.name,
  };
}
